title:             Hello Universe!
email:             hyeinkooo@gmail.com
description:       안녕!
author:            Heynie
#baseurl:           ""
url:               "https://heynie.github.io"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   heynie
#facebook_username: StartBootstrap
g-analytics:   UA-120238987-1

# Build settings
markdown:          kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

paginate:          8
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

disqus: heynie

