title:             Hello Universe!
email:             hyeinkooo@gmail.com
description:       A Blog by heynie
author:            Heynie
baseurl:           ""
url:               "http://heynie.github.io"

# Social Profiles
#twitter_username:  SBootstrap
github_username:   heynie
#facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
